/*
src:
let rec const x = let rec f y = x in f in
                let x = (1, (2, 3), (4, 5, 6)) in
                let (a, y, z) = x in
                let (b, c) = y in
                let (d, e, f) = z in
                (const (a + b + c + d + e + f)) 42
[[parse phase... begin]]
ast:
LetRec(
    FunDef {
        name: (
            Id(
                "const"
            ),
            Var(
                2
            )
        ),
        args: [
            (
                Id(
                    "x"
                ),
                Var(
                    3
                )
            )
        ],
        body: LetRec(
            FunDef {
                name: (
                    Id(
                        "f"
                    ),
                    Var(
                        0
                    )
                ),
                args: [
                    (
                        Id(
                            "y"
                        ),
                        Var(
                            1
                        )
                    )
                ],
                body: Var(
                    Id(
                        "x"
                    )
                )
            },
            Var(
                Id(
                    "f"
                )
            )
        )
    },
    Let(
        (
            Id(
                "x"
            ),
            Var(
                14
            )
        ),
        Tuple(
            [
                Int(
                    1
                ),
                Tuple(
                    [
                        Int(
                            2
                        ),
                        Int(
                            3
                        )
                    ]
                ),
                Tuple(
                    [
                        Int(
                            4
                        ),
                        Int(
                            5
                        ),
                        Int(
                            6
                        )
                    ]
                )
            ]
        ),
        LetTuple(
            [
                (
                    Id(
                        "a"
                    ),
                    Var(
                        4
                    )
                ),
                (
                    Id(
                        "y"
                    ),
                    Var(
                        5
                    )
                ),
                (
                    Id(
                        "z"
                    ),
                    Var(
                        6
                    )
                )
            ],
            Var(
                Id(
                    "x"
                )
            ),
            LetTuple(
                [
                    (
                        Id(
                            "b"
                        ),
                        Var(
                            7
                        )
                    ),
                    (
                        Id(
                            "c"
                        ),
                        Var(
                            8
                        )
                    )
                ],
                Var(
                    Id(
                        "y"
                    )
                ),
                LetTuple(
                    [
                        (
                            Id(
                                "d"
                            ),
                            Var(
                                9
                            )
                        ),
                        (
                            Id(
                                "e"
                            ),
                            Var(
                                10
                            )
                        ),
                        (
                            Id(
                                "f"
                            ),
                            Var(
                                11
                            )
                        )
                    ],
                    Var(
                        Id(
                            "z"
                        )
                    ),
                    App(
                        App(
                            Var(
                                Id(
                                    "const"
                                )
                            ),
                            [
                                Add(
                                    Add(
                                        Add(
                                            Add(
                                                Add(
                                                    Var(
                                                        Id(
                                                            "a"
                                                        )
                                                    ),
                                                    Var(
                                                        Id(
                                                            "b"
                                                        )
                                                    )
                                                ),
                                                Var(
                                                    Id(
                                                        "c"
                                                    )
                                                )
                                            ),
                                            Var(
                                                Id(
                                                    "d"
                                                )
                                            )
                                        ),
                                        Var(
                                            Id(
                                                "e"
                                            )
                                        )
                                    ),
                                    Var(
                                        Id(
                                            "f"
                                        )
                                    )
                                )
                            ],
                            Var(
                                12
                            )
                        ),
                        [
                            Int(
                                42
                            )
                        ],
                        Var(
                            13
                        )
                    )
                )
            )
        )
    )
)

[[parse phase... end]]

[[alpha transform phase... begin]]
alpha transformed ast:
LetRec(
    FunDef {
        name: (
            Id(
                "@15"
            ),
            Var(
                2
            )
        ),
        args: [
            (
                Id(
                    "@16"
                ),
                Var(
                    3
                )
            )
        ],
        body: LetRec(
            FunDef {
                name: (
                    Id(
                        "@17"
                    ),
                    Var(
                        0
                    )
                ),
                args: [
                    (
                        Id(
                            "@18"
                        ),
                        Var(
                            1
                        )
                    )
                ],
                body: Var(
                    Id(
                        "@16"
                    )
                )
            },
            Var(
                Id(
                    "@17"
                )
            )
        )
    },
    Let(
        (
            Id(
                "@19"
            ),
            Var(
                14
            )
        ),
        Tuple(
            [
                Int(
                    1
                ),
                Tuple(
                    [
                        Int(
                            2
                        ),
                        Int(
                            3
                        )
                    ]
                ),
                Tuple(
                    [
                        Int(
                            4
                        ),
                        Int(
                            5
                        ),
                        Int(
                            6
                        )
                    ]
                )
            ]
        ),
        LetTuple(
            [
                (
                    Id(
                        "@20"
                    ),
                    Var(
                        4
                    )
                ),
                (
                    Id(
                        "@21"
                    ),
                    Var(
                        5
                    )
                ),
                (
                    Id(
                        "@22"
                    ),
                    Var(
                        6
                    )
                )
            ],
            Var(
                Id(
                    "@19"
                )
            ),
            LetTuple(
                [
                    (
                        Id(
                            "@23"
                        ),
                        Var(
                            7
                        )
                    ),
                    (
                        Id(
                            "@24"
                        ),
                        Var(
                            8
                        )
                    )
                ],
                Var(
                    Id(
                        "@21"
                    )
                ),
                LetTuple(
                    [
                        (
                            Id(
                                "@25"
                            ),
                            Var(
                                9
                            )
                        ),
                        (
                            Id(
                                "@26"
                            ),
                            Var(
                                10
                            )
                        ),
                        (
                            Id(
                                "@27"
                            ),
                            Var(
                                11
                            )
                        )
                    ],
                    Var(
                        Id(
                            "@22"
                        )
                    ),
                    App(
                        App(
                            Var(
                                Id(
                                    "@15"
                                )
                            ),
                            [
                                Add(
                                    Add(
                                        Add(
                                            Add(
                                                Add(
                                                    Var(
                                                        Id(
                                                            "@20"
                                                        )
                                                    ),
                                                    Var(
                                                        Id(
                                                            "@23"
                                                        )
                                                    )
                                                ),
                                                Var(
                                                    Id(
                                                        "@24"
                                                    )
                                                )
                                            ),
                                            Var(
                                                Id(
                                                    "@25"
                                                )
                                            )
                                        ),
                                        Var(
                                            Id(
                                                "@26"
                                            )
                                        )
                                    ),
                                    Var(
                                        Id(
                                            "@27"
                                        )
                                    )
                                )
                            ],
                            Var(
                                12
                            )
                        ),
                        [
                            Int(
                                42
                            )
                        ],
                        Var(
                            13
                        )
                    )
                )
            )
        )
    )
)
[[alpha transform phase... end]]

[[typing phase... begin]]
type: Int
env:
TypeEnv {
    seq: []
}
subst:
TypeSubst {
    equations: [
        (
            0,
            Fun(
                [
                    Var(
                        1
                    )
                ],
                Var(
                    3
                )
            )
        ),
        (
            2,
            Fun(
                [
                    Var(
                        3
                    )
                ],
                Fun(
                    [
                        Var(
                            28
                        )
                    ],
                    Var(
                        3
                    )
                )
            )
        ),
        (
            14,
            Tuple(
                [
                    Int,
                    Tuple(
                        [
                            Int,
                            Int
                        ]
                    ),
                    Tuple(
                        [
                            Int,
                            Int,
                            Int
                        ]
                    )
                ]
            )
        ),
        (
            6,
            Tuple(
                [
                    Int,
                    Int,
                    Int
                ]
            )
        ),
        (
            5,
            Tuple(
                [
                    Int,
                    Int
                ]
            )
        ),
        (
            4,
            Int
        ),
        (
            8,
            Int
        ),
        (
            7,
            Int
        ),
        (
            11,
            Int
        ),
        (
            10,
            Int
        ),
        (
            9,
            Int
        ),
        (
            30,
            Int
        ),
        (
            31,
            Fun(
                [
                    Var(
                        29
                    )
                ],
                Int
            )
        ),
        (
            29,
            Int
        ),
        (
            32,
            Int
        )
    ]
}
typed ast:
LetRec(
    FunDef {
        name: (
            Id(
                "@15"
            ),
            Fun(
                [
                    Var(
                        3
                    )
                ],
                Fun(
                    [
                        Var(
                            28
                        )
                    ],
                    Var(
                        3
                    )
                )
            )
        ),
        args: [
            (
                Id(
                    "@16"
                ),
                Var(
                    3
                )
            )
        ],
        body: LetRec(
            FunDef {
                name: (
                    Id(
                        "@17"
                    ),
                    Fun(
                        [
                            Var(
                                1
                            )
                        ],
                        Var(
                            3
                        )
                    )
                ),
                args: [
                    (
                        Id(
                            "@18"
                        ),
                        Var(
                            1
                        )
                    )
                ],
                body: Var(
                    Id(
                        "@16"
                    )
                )
            },
            Var(
                Id(
                    "@17"
                )
            )
        )
    },
    Let(
        (
            Id(
                "@19"
            ),
            Tuple(
                [
                    Int,
                    Tuple(
                        [
                            Int,
                            Int
                        ]
                    ),
                    Tuple(
                        [
                            Int,
                            Int,
                            Int
                        ]
                    )
                ]
            )
        ),
        Tuple(
            [
                Int(
                    1
                ),
                Tuple(
                    [
                        Int(
                            2
                        ),
                        Int(
                            3
                        )
                    ]
                ),
                Tuple(
                    [
                        Int(
                            4
                        ),
                        Int(
                            5
                        ),
                        Int(
                            6
                        )
                    ]
                )
            ]
        ),
        LetTuple(
            [
                (
                    Id(
                        "@20"
                    ),
                    Int
                ),
                (
                    Id(
                        "@21"
                    ),
                    Tuple(
                        [
                            Int,
                            Int
                        ]
                    )
                ),
                (
                    Id(
                        "@22"
                    ),
                    Tuple(
                        [
                            Int,
                            Int,
                            Int
                        ]
                    )
                )
            ],
            Var(
                Id(
                    "@19"
                )
            ),
            LetTuple(
                [
                    (
                        Id(
                            "@23"
                        ),
                        Int
                    ),
                    (
                        Id(
                            "@24"
                        ),
                        Int
                    )
                ],
                Var(
                    Id(
                        "@21"
                    )
                ),
                LetTuple(
                    [
                        (
                            Id(
                                "@25"
                            ),
                            Int
                        ),
                        (
                            Id(
                                "@26"
                            ),
                            Int
                        ),
                        (
                            Id(
                                "@27"
                            ),
                            Int
                        )
                    ],
                    Var(
                        Id(
                            "@22"
                        )
                    ),
                    App(
                        App(
                            Var(
                                Id(
                                    "@15"
                                )
                            ),
                            [
                                Add(
                                    Add(
                                        Add(
                                            Add(
                                                Add(
                                                    Var(
                                                        Id(
                                                            "@20"
                                                        )
                                                    ),
                                                    Var(
                                                        Id(
                                                            "@23"
                                                        )
                                                    )
                                                ),
                                                Var(
                                                    Id(
                                                        "@24"
                                                    )
                                                )
                                            ),
                                            Var(
                                                Id(
                                                    "@25"
                                                )
                                            )
                                        ),
                                        Var(
                                            Id(
                                                "@26"
                                            )
                                        )
                                    ),
                                    Var(
                                        Id(
                                            "@27"
                                        )
                                    )
                                )
                            ],
                            Fun(
                                [
                                    Var(
                                        29
                                    )
                                ],
                                Int
                            )
                        ),
                        [
                            Int(
                                42
                            )
                        ],
                        Int
                    )
                )
            )
        )
    )
)
substituted type: Int
[[typing phase... end]]

[[knormal transform phase... begin]]
k-normal form:
LetRec(
    FunDef {
        name: (
            Id(
                "@15"
            ),
            Fun(
                [
                    Var(
                        3
                    )
                ],
                Fun(
                    [
                        Var(
                            28
                        )
                    ],
                    Var(
                        3
                    )
                )
            )
        ),
        args: [
            (
                Id(
                    "@16"
                ),
                Var(
                    3
                )
            )
        ],
        body: LetRec(
            FunDef {
                name: (
                    Id(
                        "@17"
                    ),
                    Fun(
                        [
                            Var(
                                1
                            )
                        ],
                        Var(
                            3
                        )
                    )
                ),
                args: [
                    (
                        Id(
                            "@18"
                        ),
                        Var(
                            1
                        )
                    )
                ],
                body: Var(
                    Id(
                        "@16"
                    )
                )
            },
            Var(
                Id(
                    "@17"
                )
            )
        )
    },
    Let(
        (
            Id(
                "@19"
            ),
            Tuple(
                [
                    Int,
                    Tuple(
                        [
                            Int,
                            Int
                        ]
                    ),
                    Tuple(
                        [
                            Int,
                            Int,
                            Int
                        ]
                    )
                ]
            )
        ),
        Let(
            (
                Id(
                    "@33"
                ),
                Int
            ),
            Int(
                1
            ),
            Let(
                (
                    Id(
                        "@36"
                    ),
                    Tuple(
                        [
                            Int,
                            Int
                        ]
                    )
                ),
                Let(
                    (
                        Id(
                            "@34"
                        ),
                        Int
                    ),
                    Int(
                        2
                    ),
                    Let(
                        (
                            Id(
                                "@35"
                            ),
                            Int
                        ),
                        Int(
                            3
                        ),
                        Tuple(
                            [
                                Id(
                                    "@34"
                                ),
                                Id(
                                    "@35"
                                )
                            ]
                        )
                    )
                ),
                Let(
                    (
                        Id(
                            "@40"
                        ),
                        Tuple(
                            [
                                Int,
                                Int,
                                Int
                            ]
                        )
                    ),
                    Let(
                        (
                            Id(
                                "@37"
                            ),
                            Int
                        ),
                        Int(
                            4
                        ),
                        Let(
                            (
                                Id(
                                    "@38"
                                ),
                                Int
                            ),
                            Int(
                                5
                            ),
                            Let(
                                (
                                    Id(
                                        "@39"
                                    ),
                                    Int
                                ),
                                Int(
                                    6
                                ),
                                Tuple(
                                    [
                                        Id(
                                            "@37"
                                        ),
                                        Id(
                                            "@38"
                                        ),
                                        Id(
                                            "@39"
                                        )
                                    ]
                                )
                            )
                        )
                    ),
                    Tuple(
                        [
                            Id(
                                "@33"
                            ),
                            Id(
                                "@36"
                            ),
                            Id(
                                "@40"
                            )
                        ]
                    )
                )
            )
        ),
        LetTuple(
            [
                (
                    Id(
                        "@20"
                    ),
                    Int
                ),
                (
                    Id(
                        "@21"
                    ),
                    Tuple(
                        [
                            Int,
                            Int
                        ]
                    )
                ),
                (
                    Id(
                        "@22"
                    ),
                    Tuple(
                        [
                            Int,
                            Int,
                            Int
                        ]
                    )
                )
            ],
            Id(
                "@19"
            ),
            LetTuple(
                [
                    (
                        Id(
                            "@23"
                        ),
                        Int
                    ),
                    (
                        Id(
                            "@24"
                        ),
                        Int
                    )
                ],
                Id(
                    "@21"
                ),
                LetTuple(
                    [
                        (
                            Id(
                                "@25"
                            ),
                            Int
                        ),
                        (
                            Id(
                                "@26"
                            ),
                            Int
                        ),
                        (
                            Id(
                                "@27"
                            ),
                            Int
                        )
                    ],
                    Id(
                        "@22"
                    ),
                    Let(
                        (
                            Id(
                                "@56"
                            ),
                            Fun(
                                [
                                    Var(
                                        29
                                    )
                                ],
                                Int
                            )
                        ),
                        Let(
                            (
                                Id(
                                    "@55"
                                ),
                                Int
                            ),
                            Let(
                                (
                                    Id(
                                        "@53"
                                    ),
                                    Int
                                ),
                                Let(
                                    (
                                        Id(
                                            "@51"
                                        ),
                                        Int
                                    ),
                                    Let(
                                        (
                                            Id(
                                                "@49"
                                            ),
                                            Int
                                        ),
                                        Let(
                                            (
                                                Id(
                                                    "@47"
                                                ),
                                                Int
                                            ),
                                            Add(
                                                Id(
                                                    "@20"
                                                ),
                                                Id(
                                                    "@23"
                                                )
                                            ),
                                            Add(
                                                Id(
                                                    "@47"
                                                ),
                                                Id(
                                                    "@24"
                                                )
                                            )
                                        ),
                                        Add(
                                            Id(
                                                "@49"
                                            ),
                                            Id(
                                                "@25"
                                            )
                                        )
                                    ),
                                    Add(
                                        Id(
                                            "@51"
                                        ),
                                        Id(
                                            "@26"
                                        )
                                    )
                                ),
                                Add(
                                    Id(
                                        "@53"
                                    ),
                                    Id(
                                        "@27"
                                    )
                                )
                            ),
                            App(
                                Id(
                                    "@15"
                                ),
                                [
                                    Id(
                                        "@55"
                                    )
                                ]
                            )
                        ),
                        Let(
                            (
                                Id(
                                    "@57"
                                ),
                                Int
                            ),
                            Int(
                                42
                            ),
                            App(
                                Id(
                                    "@56"
                                ),
                                [
                                    Id(
                                        "@57"
                                    )
                                ]
                            )
                        )
                    )
                )
            )
        )
    )
)
k-normal form type:
Int
flatted k-normal form:
LetRec(
    FunDef {
        name: (
            Id(
                "@15"
            ),
            Fun(
                [
                    Var(
                        3
                    )
                ],
                Fun(
                    [
                        Var(
                            28
                        )
                    ],
                    Var(
                        3
                    )
                )
            )
        ),
        args: [
            (
                Id(
                    "@16"
                ),
                Var(
                    3
                )
            )
        ],
        body: LetRec(
            FunDef {
                name: (
                    Id(
                        "@17"
                    ),
                    Fun(
                        [
                            Var(
                                1
                            )
                        ],
                        Var(
                            3
                        )
                    )
                ),
                args: [
                    (
                        Id(
                            "@18"
                        ),
                        Var(
                            1
                        )
                    )
                ],
                body: Var(
                    Id(
                        "@16"
                    )
                )
            },
            Var(
                Id(
                    "@17"
                )
            )
        )
    },
    Let(
        (
            Id(
                "@33"
            ),
            Int
        ),
        Int(
            1
        ),
        Let(
            (
                Id(
                    "@34"
                ),
                Int
            ),
            Int(
                2
            ),
            Let(
                (
                    Id(
                        "@35"
                    ),
                    Int
                ),
                Int(
                    3
                ),
                Let(
                    (
                        Id(
                            "@36"
                        ),
                        Tuple(
                            [
                                Int,
                                Int
                            ]
                        )
                    ),
                    Tuple(
                        [
                            Id(
                                "@34"
                            ),
                            Id(
                                "@35"
                            )
                        ]
                    ),
                    Let(
                        (
                            Id(
                                "@37"
                            ),
                            Int
                        ),
                        Int(
                            4
                        ),
                        Let(
                            (
                                Id(
                                    "@38"
                                ),
                                Int
                            ),
                            Int(
                                5
                            ),
                            Let(
                                (
                                    Id(
                                        "@39"
                                    ),
                                    Int
                                ),
                                Int(
                                    6
                                ),
                                Let(
                                    (
                                        Id(
                                            "@40"
                                        ),
                                        Tuple(
                                            [
                                                Int,
                                                Int,
                                                Int
                                            ]
                                        )
                                    ),
                                    Tuple(
                                        [
                                            Id(
                                                "@37"
                                            ),
                                            Id(
                                                "@38"
                                            ),
                                            Id(
                                                "@39"
                                            )
                                        ]
                                    ),
                                    Let(
                                        (
                                            Id(
                                                "@19"
                                            ),
                                            Tuple(
                                                [
                                                    Int,
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int
                                                        ]
                                                    ),
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int,
                                                            Int
                                                        ]
                                                    )
                                                ]
                                            )
                                        ),
                                        Tuple(
                                            [
                                                Id(
                                                    "@33"
                                                ),
                                                Id(
                                                    "@36"
                                                ),
                                                Id(
                                                    "@40"
                                                )
                                            ]
                                        ),
                                        LetTuple(
                                            [
                                                (
                                                    Id(
                                                        "@20"
                                                    ),
                                                    Int
                                                ),
                                                (
                                                    Id(
                                                        "@21"
                                                    ),
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int
                                                        ]
                                                    )
                                                ),
                                                (
                                                    Id(
                                                        "@22"
                                                    ),
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int,
                                                            Int
                                                        ]
                                                    )
                                                )
                                            ],
                                            Id(
                                                "@19"
                                            ),
                                            LetTuple(
                                                [
                                                    (
                                                        Id(
                                                            "@23"
                                                        ),
                                                        Int
                                                    ),
                                                    (
                                                        Id(
                                                            "@24"
                                                        ),
                                                        Int
                                                    )
                                                ],
                                                Id(
                                                    "@21"
                                                ),
                                                LetTuple(
                                                    [
                                                        (
                                                            Id(
                                                                "@25"
                                                            ),
                                                            Int
                                                        ),
                                                        (
                                                            Id(
                                                                "@26"
                                                            ),
                                                            Int
                                                        ),
                                                        (
                                                            Id(
                                                                "@27"
                                                            ),
                                                            Int
                                                        )
                                                    ],
                                                    Id(
                                                        "@22"
                                                    ),
                                                    Let(
                                                        (
                                                            Id(
                                                                "@47"
                                                            ),
                                                            Int
                                                        ),
                                                        Add(
                                                            Id(
                                                                "@20"
                                                            ),
                                                            Id(
                                                                "@23"
                                                            )
                                                        ),
                                                        Let(
                                                            (
                                                                Id(
                                                                    "@49"
                                                                ),
                                                                Int
                                                            ),
                                                            Add(
                                                                Id(
                                                                    "@47"
                                                                ),
                                                                Id(
                                                                    "@24"
                                                                )
                                                            ),
                                                            Let(
                                                                (
                                                                    Id(
                                                                        "@51"
                                                                    ),
                                                                    Int
                                                                ),
                                                                Add(
                                                                    Id(
                                                                        "@49"
                                                                    ),
                                                                    Id(
                                                                        "@25"
                                                                    )
                                                                ),
                                                                Let(
                                                                    (
                                                                        Id(
                                                                            "@53"
                                                                        ),
                                                                        Int
                                                                    ),
                                                                    Add(
                                                                        Id(
                                                                            "@51"
                                                                        ),
                                                                        Id(
                                                                            "@26"
                                                                        )
                                                                    ),
                                                                    Let(
                                                                        (
                                                                            Id(
                                                                                "@55"
                                                                            ),
                                                                            Int
                                                                        ),
                                                                        Add(
                                                                            Id(
                                                                                "@53"
                                                                            ),
                                                                            Id(
                                                                                "@27"
                                                                            )
                                                                        ),
                                                                        Let(
                                                                            (
                                                                                Id(
                                                                                    "@56"
                                                                                ),
                                                                                Fun(
                                                                                    [
                                                                                        Var(
                                                                                            29
                                                                                        )
                                                                                    ],
                                                                                    Int
                                                                                )
                                                                            ),
                                                                            App(
                                                                                Id(
                                                                                    "@15"
                                                                                ),
                                                                                [
                                                                                    Id(
                                                                                        "@55"
                                                                                    )
                                                                                ]
                                                                            ),
                                                                            Let(
                                                                                (
                                                                                    Id(
                                                                                        "@57"
                                                                                    ),
                                                                                    Int
                                                                                ),
                                                                                Int(
                                                                                    42
                                                                                ),
                                                                                App(
                                                                                    Id(
                                                                                        "@56"
                                                                                    ),
                                                                                    [
                                                                                        Id(
                                                                                            "@57"
                                                                                        )
                                                                                    ]
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)
[[knormal transform phase... end]]

[[closure transform phase... begin]]
known set {Label("@15")}
program:
Program {
    decls: [
        Function {
            entry: (
                Label(
                    "@17"
                ),
                Fun(
                    [
                        Var(
                            1
                        )
                    ],
                    Var(
                        3
                    )
                )
            ),
            free_variables: {
                Id(
                    "@16"
                ): Var(
                    3
                )
            },
            args: [
                (
                    Id(
                        "@18"
                    ),
                    Var(
                        1
                    )
                )
            ],
            body: Var(
                Id(
                    "@16"
                )
            )
        },
        Function {
            entry: (
                Label(
                    "@15"
                ),
                Fun(
                    [
                        Var(
                            3
                        )
                    ],
                    Fun(
                        [
                            Var(
                                28
                            )
                        ],
                        Var(
                            3
                        )
                    )
                )
            ),
            free_variables: {},
            args: [
                (
                    Id(
                        "@16"
                    ),
                    Var(
                        3
                    )
                )
            ],
            body: MakeClosure(
                Id(
                    "@17"
                ),
                Closure {
                    entry: Label(
                        "@17"
                    ),
                    free_variables: {
                        Id(
                            "@16"
                        )
                    }
                },
                Var(
                    Id(
                        "@17"
                    )
                )
            )
        }
    ],
    code: Let(
        (
            Id(
                "@33"
            ),
            Int
        ),
        Int(
            1
        ),
        Let(
            (
                Id(
                    "@34"
                ),
                Int
            ),
            Int(
                2
            ),
            Let(
                (
                    Id(
                        "@35"
                    ),
                    Int
                ),
                Int(
                    3
                ),
                Let(
                    (
                        Id(
                            "@36"
                        ),
                        Tuple(
                            [
                                Int,
                                Int
                            ]
                        )
                    ),
                    Tuple(
                        [
                            Id(
                                "@34"
                            ),
                            Id(
                                "@35"
                            )
                        ]
                    ),
                    Let(
                        (
                            Id(
                                "@37"
                            ),
                            Int
                        ),
                        Int(
                            4
                        ),
                        Let(
                            (
                                Id(
                                    "@38"
                                ),
                                Int
                            ),
                            Int(
                                5
                            ),
                            Let(
                                (
                                    Id(
                                        "@39"
                                    ),
                                    Int
                                ),
                                Int(
                                    6
                                ),
                                Let(
                                    (
                                        Id(
                                            "@40"
                                        ),
                                        Tuple(
                                            [
                                                Int,
                                                Int,
                                                Int
                                            ]
                                        )
                                    ),
                                    Tuple(
                                        [
                                            Id(
                                                "@37"
                                            ),
                                            Id(
                                                "@38"
                                            ),
                                            Id(
                                                "@39"
                                            )
                                        ]
                                    ),
                                    Let(
                                        (
                                            Id(
                                                "@19"
                                            ),
                                            Tuple(
                                                [
                                                    Int,
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int
                                                        ]
                                                    ),
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int,
                                                            Int
                                                        ]
                                                    )
                                                ]
                                            )
                                        ),
                                        Tuple(
                                            [
                                                Id(
                                                    "@33"
                                                ),
                                                Id(
                                                    "@36"
                                                ),
                                                Id(
                                                    "@40"
                                                )
                                            ]
                                        ),
                                        LetTuple(
                                            [
                                                (
                                                    Id(
                                                        "@20"
                                                    ),
                                                    Int
                                                ),
                                                (
                                                    Id(
                                                        "@21"
                                                    ),
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int
                                                        ]
                                                    )
                                                ),
                                                (
                                                    Id(
                                                        "@22"
                                                    ),
                                                    Tuple(
                                                        [
                                                            Int,
                                                            Int,
                                                            Int
                                                        ]
                                                    )
                                                )
                                            ],
                                            Id(
                                                "@19"
                                            ),
                                            LetTuple(
                                                [
                                                    (
                                                        Id(
                                                            "@23"
                                                        ),
                                                        Int
                                                    ),
                                                    (
                                                        Id(
                                                            "@24"
                                                        ),
                                                        Int
                                                    )
                                                ],
                                                Id(
                                                    "@21"
                                                ),
                                                LetTuple(
                                                    [
                                                        (
                                                            Id(
                                                                "@25"
                                                            ),
                                                            Int
                                                        ),
                                                        (
                                                            Id(
                                                                "@26"
                                                            ),
                                                            Int
                                                        ),
                                                        (
                                                            Id(
                                                                "@27"
                                                            ),
                                                            Int
                                                        )
                                                    ],
                                                    Id(
                                                        "@22"
                                                    ),
                                                    Let(
                                                        (
                                                            Id(
                                                                "@47"
                                                            ),
                                                            Int
                                                        ),
                                                        Add(
                                                            Id(
                                                                "@20"
                                                            ),
                                                            Id(
                                                                "@23"
                                                            )
                                                        ),
                                                        Let(
                                                            (
                                                                Id(
                                                                    "@49"
                                                                ),
                                                                Int
                                                            ),
                                                            Add(
                                                                Id(
                                                                    "@47"
                                                                ),
                                                                Id(
                                                                    "@24"
                                                                )
                                                            ),
                                                            Let(
                                                                (
                                                                    Id(
                                                                        "@51"
                                                                    ),
                                                                    Int
                                                                ),
                                                                Add(
                                                                    Id(
                                                                        "@49"
                                                                    ),
                                                                    Id(
                                                                        "@25"
                                                                    )
                                                                ),
                                                                Let(
                                                                    (
                                                                        Id(
                                                                            "@53"
                                                                        ),
                                                                        Int
                                                                    ),
                                                                    Add(
                                                                        Id(
                                                                            "@51"
                                                                        ),
                                                                        Id(
                                                                            "@26"
                                                                        )
                                                                    ),
                                                                    Let(
                                                                        (
                                                                            Id(
                                                                                "@55"
                                                                            ),
                                                                            Int
                                                                        ),
                                                                        Add(
                                                                            Id(
                                                                                "@53"
                                                                            ),
                                                                            Id(
                                                                                "@27"
                                                                            )
                                                                        ),
                                                                        Let(
                                                                            (
                                                                                Id(
                                                                                    "@56"
                                                                                ),
                                                                                Fun(
                                                                                    [
                                                                                        Var(
                                                                                            29
                                                                                        )
                                                                                    ],
                                                                                    Int
                                                                                )
                                                                            ),
                                                                            AppDirect(
                                                                                Label(
                                                                                    "@15"
                                                                                ),
                                                                                [
                                                                                    Id(
                                                                                        "@55"
                                                                                    )
                                                                                ]
                                                                            ),
                                                                            Let(
                                                                                (
                                                                                    Id(
                                                                                        "@57"
                                                                                    ),
                                                                                    Int
                                                                                ),
                                                                                Int(
                                                                                    42
                                                                                ),
                                                                                AppClosure(
                                                                                    Id(
                                                                                        "@56"
                                                                                    ),
                                                                                    [
                                                                                        Id(
                                                                                            "@57"
                                                                                        )
                                                                                    ]
                                                                                )
                                                                            )
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
}
[[closure transform phase... end]]

*/


#include<stdio.h>
#include<stdlib.h>
#include<stdarg.h>

#define alloc_heap malloc

typedef void (*func_type)(void);
typedef long long i64;
typedef long long bool;
typedef unsigned char unit;

struct value {
    void* p;
};

struct closure {
    func_type func;
    i64 fv_num;
    struct value fv[0];
};

struct tuple {
    i64 num;
    struct value elem[0];
};

int stack_top = -1;
struct value stack_pool[0xffff];

void push(struct value x){
    stack_top++;
    stack_pool[stack_top] = x;
}

struct value pop(void){
    struct value r = stack_pool[stack_top];
    stack_top--;
    return r;
}

struct value make_unit(void){
    struct value r;
    r.p = alloc_heap(sizeof(unit));
    *(unit*)(r.p) = 0xff;
    return r;
}

struct value make_int(i64 i){
    struct value r;
    r.p = alloc_heap(sizeof(i64));
    *(i64*)(r.p) = i;
    return r;
}

struct value make_bool(bool b){
    struct value r;
    r.p = alloc_heap(sizeof(bool));
    *(bool*)(r.p) = b;
    return r;
}

struct value make_closure(func_type func, i64 fv_num, ...){
    struct value r;
    va_list args;

    r.p = alloc_heap(sizeof(struct closure)+sizeof(struct value)*fv_num);
    ((struct closure*)(r.p))->func = func;
    ((struct closure*)(r.p))->fv_num = fv_num;

    va_start(args,fv_num);
    for(int i=0;i<fv_num;i++)
        ((struct closure*)(r.p))->fv[i] = va_arg(args, struct value);
    va_end(args);

    return r;
}

struct value make_tuple(i64 num, ...){
    struct value r;
    va_list args;

    r.p = alloc_heap(sizeof(struct tuple)+sizeof(struct value)*num);
    ((struct tuple*)(r.p))->num = num;

    va_start(args,num);
    for(int i=0;i<num;i++)
        ((struct tuple*)(r.p))->elem[i] = va_arg(args, struct value);
    va_end(args);

    return r;
}


void func17(void){
    struct value var18 = pop(); // arg
    struct value var16 = pop(); // fv
    push(var16);
}
void func15(void){
    struct value var16 = pop(); // arg
    struct value var17 = make_closure( func17, 1, var16);
    push(var17);
}
void entry_point(void){
    push(make_int(1));
    struct value var33 = pop();
    push(make_int(2));
    struct value var34 = pop();
    push(make_int(3));
    struct value var35 = pop();
    push(make_tuple(2, var34, var35));
    struct value var36 = pop();
    push(make_int(4));
    struct value var37 = pop();
    push(make_int(5));
    struct value var38 = pop();
    push(make_int(6));
    struct value var39 = pop();
    push(make_tuple(3, var37, var38, var39));
    struct value var40 = pop();
    push(make_tuple(3, var33, var36, var40));
    struct value var19 = pop();
    struct value var20 = ((struct tuple*)(var19.p))->elem[0];
    struct value var21 = ((struct tuple*)(var19.p))->elem[1];
    struct value var22 = ((struct tuple*)(var19.p))->elem[2];
    struct value var23 = ((struct tuple*)(var21.p))->elem[0];
    struct value var24 = ((struct tuple*)(var21.p))->elem[1];
    struct value var25 = ((struct tuple*)(var22.p))->elem[0];
    struct value var26 = ((struct tuple*)(var22.p))->elem[1];
    struct value var27 = ((struct tuple*)(var22.p))->elem[2];
    push(make_int(*(i64*)(var20.p) + *(i64*)(var23.p)));
    struct value var47 = pop();
    push(make_int(*(i64*)(var47.p) + *(i64*)(var24.p)));
    struct value var49 = pop();
    push(make_int(*(i64*)(var49.p) + *(i64*)(var25.p)));
    struct value var51 = pop();
    push(make_int(*(i64*)(var51.p) + *(i64*)(var26.p)));
    struct value var53 = pop();
    push(make_int(*(i64*)(var53.p) + *(i64*)(var27.p)));
    struct value var55 = pop();
    push(var55);
    func15();
    struct value var56 = pop();
    push(make_int(42));
    struct value var57 = pop();
    for(int i=((struct closure *)(var56.p))->fv_num-1; i >= 0;i--) push(((struct closure *)(var56.p))->fv[i]);
    push(var57);
    ((struct closure *)(var56.p))->func();
}

void print_result(void){
    struct value r = pop();

    printf("result: %lld\n", *(i64*)(r.p));

}

int main(void){
    entry_point();
    print_result();
    return 0;
}

